# Site settings
title: Shannon Holloway
email: info@shannonholloway.com
description: Shannon Holloway
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_s_holloway
github_username:  github_hybridartist

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/



